#!/usr/bin/env bash

# get domain and subdomain parameters
if [ "$#" -eq 2 ];
then 
    DOMAIN="$1"
    SUBDOMAIN="$2"
else
    DOMAIN="$1"
fi

# get ip address for specified subdomain
function get_ip() {
    IP=$(dig "$1"."$DOMAIN" | grep -A1 "ANSWER SECTION:" | grep -A0 "$DOMAIN" | awk '{print $5}')
    echo "$IP" 
}
# get the record type for specified subdomain
function get_record_type() {
    # echo $1
    RECORD_TYPE=$(dig "$1"."$DOMAIN" | grep -A1 "ANSWER SECTION:" | grep -A0 "$DOMAIN" | awk '{print $4}')
    echo "$RECORD_TYPE"
}


subdomain_list=("www" "lb-01" "web-01" "web-02")

if [ "$#" -eq 1 ];
then
   
    for s_domain in "${subdomain_list[@]}"
    do
        ip=$(get_ip "$s_domain")
        type=$(get_record_type "$s_domain")
        echo "The subdomain $s_domain is a $type record and points to $ip"
    done

elif [ "$#" -eq 2 ];
then
    ip=$(get_ip "$SUBDOMAIN")
    type=$(get_record_type "$SUBDOMAIN")
    echo "The subdomain $SUBDOMAIN is a $type record and points to $ip"

fi